[package]
name = "yew-data-fetch"
version = "0.1.0"
authors = ["sadness_ojisan <sadness.ojisan@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.38"
serde = "1.0.123"
wasm-bindgen = "0.2.69"
yew = "0.17.4"
